name: Transform tokens send from figma
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    # and the event_type property from the request body is 'update-tokens'
    types: [update-tokens]

jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: mkdir "tokens" directory
        run: 'mkdir -p tokens'

      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          # it uses the figma filename that was send as then filename parameter
          name: ${{ github.event.client_payload.filename }}
          # it uses the json string that was send as the tokens parameter
          json: ${{ github.event.client_payload.tokens }}
          # it uses the directory named "tokens" to store this json file (change this if you changed it above to use a different folder)
          dir: 'tokens'

      - name: run prettier on json file
        run: npx prettier --write tokens/*.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ${{ github.event.client_payload.commitMessage || 'Tokens updated' }}
          title: 'Design tokens updated #${{github.run_id}}'
          body: 'Design tokens have been updated via Figma and need to be reviewed.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
